# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Archive-Any
version:      0.09
version_from: lib/Archive/Any.pm
installdirs:  site
requires:
    Archive::Tar:                  0.22
    Archive::Zip:                  1.07
    Cwd:                           0
    File::MMagic:                  1.27
    File::Spec::Functions:         0
    MIME::Types:                   1.16
    Module::Find:                  0.05
    Test::More:                    0.4
    Test::Warn:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
