--- #YAML:1.0
name:                Archive-Any
version:             0.093
abstract:            ~
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_03
author:              ~
distribution_type:   module
requires:     
    Archive::Tar:                  0.22
    Archive::Zip:                  1.07
    Cwd:                           0
    File::MMagic:                  1.27
    File::Spec::Functions:         0
    MIME::Types:                   1.16
    Module::Find:                  0.05
    Test::More:                    0.4
    Test::Warn:                    0
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
